Fixed buld errors caused by GitHub Metadata
GitHub Metadata: Error processing value 'baseurl':
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    No repo name found. Specify using PAGES_REPO_NWO environment variables, 'repository' in your configuration, or set up an 'origin' git remote pointing to your github.com repository.

Related issues
https://github.com/github/pages-gem/issues/399
https://github.com/jekyll/jekyll/issues/4705